name: "Dependabot Review Assign"
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Find last assign
        if: contains(github.actor, 'dependabot')
        uses: lee-dohm/last-assigned@v1
        with:
          query: 'label:dependencies assignee:*'
          token: ${{ secrets.GITHUB_TOKEN }}
        id: assigned
      - uses: lee-dohm/team-rotation@v1
        if: contains(github.actor, 'dependabot')
        with:
          last: ${{ steps.assigned.outputs.last }}
          include: toby-daigle JsGarneau julienchouinard jeremilc Pierregagne
        id: rotation
      - name: 'Add assignee'
        if: contains(github.actor, 'dependabot')
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: ${{ steps.rotation.outputs.next }}
